Logging tools
getditto/ditto_flutter_tools pull request #17
Opened 2024-11-22 13:52 UTC by cameron1024

Adds logging tools:
 - `LogLevelSwitch` - allows setting the minimum log level (or disable logs)
 - `SaveLogsButton`, `ShareLogsButton`, `SaveOrShareLogsButtons` allow exporting the logs
 - `LoggingTools` is a whole page containing log-related tools

Also adds `AllTools`, which is a UI that provides all the tools that we reasonably can without significant user configuration.

It currently has a placeholder page, because `BottomNavigationBar` requires at least two children.
It will have the sync status view, but that needs some changes to be able to infer the list of subscriptions from the current ditto instance, which IMO belong in a different PR.

2024-11-22 15:18 UTC, bplattenburg commented
I think this maps to https://github.com/getditto/ditto_flutter_tools/issues/7?

2024-11-22 18:46 UTC, rajramsaroop approved these changes
Based on my extremely limited knowledge of Flutter and comparing with the Android tools, this looks good to me :D

2024-11-22 18:57 UTC, bplattenburg requested changes
Can we make sure to include some `README` instructions (and ideally screenshots) around how the tool works and how to use it? I imagine most of it can be copied from one of the other platforms & tweaked for Flutter.

2025-03-31 17:22 UTC, bplattenburg commented
Closing as we've decided to not pursue this tool further - the SDK provides this out of the box in recent releases

2025-03-31 17:22 UTC, closed without merging